services:
  backend:
    image: hasangi123/forever-fashion-app-backend:latest
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://hasangidahanayake:hasangi123@cluster0.6wssoxp.mongodb.net
      - CLOUDINARY_NAME=dzqhcetwo
      - CLOUDINARY_API_KEY=898722333981874
      - CLOUDINARY_SECRET_KEY=QlDp5aelUnd8Gi-_p7nGsW25XT8
      -_EMAIL=admin@123.com
      -ADMIN_PASSWORD=admin123
      - JWT_SECRET=hasangi
    restart: always

  frontend:
    image: hasangi123/forever-fashion-app-frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://13.234.116.85:4000
    restart: always

  admin:
    image: hasangi123/forever-fashion-app-admin:latest
    container_name: admin
    ports:
      - "5174:5174"
    environment:
      - VITE_BACKEND_URL=http://13.234.116.85:4000
    restart: always